In [1]:
# Compare three different algorithms: Dynamic Pricing, Adaptive Pricing, and FCFS
# Use intercepts and slopes from initialization.py as starting point for linear demand curve
# Dynamic Pricing: 
    # Retail Price Optimization at InterContinental Hotels Group. 
    # INFORMS Journal on Applied Analytics 42(1):45-57. 
    # https://doi.org/10.1287/inte.1110.0620

# Adaptibe Pricing: Developed by me, adapted from:
    # Revenue Management Without Forecasting or Optimization: An Adaptive Algorithm for Determining Airline Seat Protection Levels
    # Management Science 46(6):760-775.
    # https://doi.org/10.1287/mnsc.46.6.760.11936
    
# FCFS: First-Come, First-Serve

In [2]:
import itertools
import numpy as np
from scipy.optimize import linprog
from cvxopt import matrix, solvers, spmatrix
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

from initialize import linparams

In [3]:
# Parameter values
n_class = 2
los = 3
capacity = 50
intensity = 1.5
slope_init = np.array([-0.1, -0.15])
rates_init = np.array([[135, 135, 135, 135, 135, 108, 108],
                       [115, 115, 115, 115, 115, 92, 92]])
combs = n_class * 7 * los

In [4]:
# intercepts and slopes for rate class, arrival day of week and los combination
params = linparams(capacity, intensity, slope_init, rates_init)

In [5]:
# Starting parameters
params_slopes = params[0]
params_intercepts = params[1]

In [6]:
params_slopes

array([[[-0.13497418, -0.10652144, -0.07113071],
        [-0.08184909, -0.08869425, -0.08195652],
        [-0.07653131, -0.07536646, -0.07329343],
        [-0.0759857 , -0.11634877, -0.08363741],
        [-0.0842692 , -0.11237746, -0.07390998],
        [-0.10643519, -0.1016219 , -0.06129235],
        [-0.1127791 , -0.07460933, -0.05866961]],

       [[-0.14259857, -0.13969252, -0.10478659],
        [-0.1631681 , -0.16051354, -0.10965796],
        [-0.1277074 , -0.12751371, -0.10586564],
        [-0.20356976, -0.15715259, -0.1594383 ],
        [-0.17334248, -0.14203521, -0.10800819],
        [-0.13103278, -0.13269145, -0.11948423],
        [-0.16572495, -0.12556131, -0.13836831]]])

In [7]:
# Calculate averate rates for each arrival day of week and los combination
rates_arrival_los = [[rates_init[i, j],
                      rates_init[i, j] + rates_init[i, (j+1)%7],
                      rates_init[i, j] + rates_init[i, (j+1)%7] + rates_init[i, (j+2)%7]] 
                      for i, j in itertools.product(range(n_class), range(7))]
# Store it as a numpy array
rates_arrival_los = np.array(rates_arrival_los).reshape(n_class, 7, los)

In [8]:
rates_arrival_los

array([[[135, 270, 405],
        [135, 270, 405],
        [135, 270, 405],
        [135, 270, 378],
        [135, 243, 351],
        [108, 216, 351],
        [108, 243, 378]],

       [[115, 230, 345],
        [115, 230, 345],
        [115, 230, 345],
        [115, 230, 322],
        [115, 207, 299],
        [ 92, 184, 299],
        [ 92, 207, 322]]])

In [9]:
# Coefficients of objective function for LP
obj_coefs = (-1) * rates_arrival_los.reshape(n_class * 7 * los)
obj_coefs

array([-135, -270, -405, -135, -270, -405, -135, -270, -405, -135, -270,
       -378, -135, -243, -351, -108, -216, -351, -108, -243, -378, -115,
       -230, -345, -115, -230, -345, -115, -230, -345, -115, -230, -322,
       -115, -207, -299,  -92, -184, -299,  -92, -207, -322])

In [10]:
# Inequality equations, LHS
# We have total number of 42 decision veriables, corresponding to total number of
# rate class, arrival day of week and los combinations.
# Column indexes 0-20 are associated with decision variables for rate class 1
# Column indexes 21-41 are associated with decision variables for rate class 2
G = np.zeros(7 * los * n_class * 7).reshape(7, n_class*7*los)
# Arrivals that span Sunday stay night for rate class 1
G[0,:(7*los)] = [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# Arrivals that span Monday stay night for rate class 1
G[1,:(7*los)] = [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
G[2,:(7*los)] = [0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
G[3,:(7*los)] = [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
G[4,:(7*los)] = [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
G[5,:(7*los)] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0]
G[6,:(7*los)] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1]
# Arrivals that span Sunday stay night for rate class 2
G[0,(7*los):] = [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# Arrivals that span Monday stay night for rate class 2
G[1,(7*los):] = [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
G[2,(7*los):] = [0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
G[3,(7*los):] = [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
G[4,(7*los):] = [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
G[5,(7*los):] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0]
G[6,(7*los):] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1]

# identity matrix for expected demand constraints, G for capacity constraints,
# Negative identity matrix for non-negativity
G = np.concatenate((np.identity(combs), G, -np.identity(combs)), axis=0)
# Inequality equations, RHS
# For each rate class, number of arrivals for a stay night in question is half of
# expected demand, which is capacity * intensity, then this expected demand is equally 
# split between 6 arrival day, los combination that spans the stay night in question
expDemand_each = (capacity * intensity * 0.5) / 6
h = np.round(expDemand_each, decimals=0) * np.ones(n_class * 7 * los)
# First h for expected demand, second component for capacity rhs
# Third component for non-negativity rhs.
h = np.concatenate((h, capacity * np.ones(7), np.zeros(combs)), axis=0)

In [11]:
h

array([ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  6.,  6., 50., 50., 50., 50., 50., 50., 50.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [12]:
# Convert numpy arrays to cvxopt matrix forms
c = matrix(obj_coefs, tc='d')
G = matrix(G)
h = matrix(h)

In [13]:
# Solve LP, method = "interior point method" by default
# Results are used for initialization purpose (warm start), so it should
# not affect final algorithm performance after an efficient number of runs
sol = solvers.lp(c, G, h)

     pcost       dcost       gap    pres   dres   k/t
 0: -4.3576e+04 -1.0770e+05  5e+04  1e-01  8e-01  1e+00
 1: -4.4750e+04 -7.3030e+04  2e+04  7e-02  4e-01  5e+01
 2: -4.5974e+04 -5.1996e+04  3e+03  1e-02  8e-02  2e+01
 3: -4.6445e+04 -4.7593e+04  6e+02  3e-03  1e-02  3e+00
 4: -4.6520e+04 -4.6801e+04  2e+02  7e-04  4e-03  1e+00
 5: -4.6547e+04 -4.6554e+04  3e+00  1e-05  8e-05  3e-02
 6: -4.6548e+04 -4.6548e+04  3e-02  1e-07  8e-07  3e-04
 7: -4.6548e+04 -4.6548e+04  3e-04  1e-09  8e-09  3e-06
Optimal solution found.


In [14]:
# Optimal solutions serve as booking limits: number of booking requests to accept for 
# a given rate class, arrival day, los combination
bkLimits = np.array(sol['x']).reshape(n_class, 7, los)
bkLimits = np.round(bkLimits, decimals=0)
bkLimits

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [2., 6., 6.]],

       [[6., 6., 6.],
        [4., 2., 2.],
        [1., 1., 2.],
        [3., 3., 3.],
        [3., 3., 0.],
        [2., 0., 6.],
        [0., 6., 6.]]])

In [60]:
# Dual values associated with demand constraints
# Represent marginal contribution for the stay night revenue
duals = np.array(sol['z'])[:(n_class*7*los)].reshape(n_class, 7, los)
duals = np.round(duals, decimals=0)
duals

array([[[135., 155., 175.],
        [ 20.,  40.,  60.],
        [ 20.,  40.,  60.],
        [ 20.,  40.,  56.],
        [ 20.,  36.,  36.],
        [ 16.,  16., 151.],
        [  0., 135., 270.]],

       [[115., 115., 115.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,  99.],
        [  0.,  99., 214.]]])

In [61]:
# '012' represents rate class 1, Monday arrival and 3-night stay
sun_stay_index = ['000', '001', '002', '061', '062', '052', 
            '100', '101', '102', '161', '162', '152']

mon_stay_index = ['010', '011', '012', '001', '002', '062', 
            '110', '111', '112', '101', '102', '162']

tue_stay_index = ['020', '021', '022', '011', '012', '002', 
            '120', '121', '122', '111', '112', '102']

wed_stay_index = ['030', '031', '032', '021', '022', '012', 
            '130', '131', '132', '121', '122', '112']

thr_stay_index = ['040', '041', '042', '031', '032', '022', 
            '140', '141', '142', '131', '132', '122']

fri_stay_index = ['050', '051', '052', '041', '042', '032', 
            '150', '151', '152', '141', '142', '132']

sat_stay_index = ['060', '061', '062', '051', '052', '042', 
            '160', '161', '162', '151', '152', '142']

In [68]:
# Create virtual buckets with booking classes in them
sun_stay_index_cp = sun_stay_index.copy()
max_buckets = 5
buckets = [[] for i in range(max_buckets)]
n_buckets = 1

while n_buckets <= max_buckets and sun_duals:
    sun_duals_left = [duals[int(item[0]), int(item[1]), int(item[2])] for item in sun_stay_index_cp]
    sun_duals_max = np.max(sun_duals_left)
    lower = ((max_buckets-n_buckets) / (max_buckets-n_buckets+1)) * sun_duals_max
    upper = sun_duals_max
    print(lower, upper)
    print(sun_stay_index_cp)
    
    for item in sun_stay_index_cp:
        # rate class
        r_index = int(item[0])
        # arrival day of week
        a_index = int(item[1])
        # duration (los)
        d_index = int(item[2])
        if duals[r_index, a_index, d_index] >= lower and duals[r_index, a_index, d_index] <= upper:
            buckets[n_buckets-1].append(item)
            sun_stay_index_cp.remove(item)
            
    print(sun_stay_index_cp)
            
    n_buckets += 1
    

216.0 270.0
['000', '001', '002', '061', '062', '052', '100', '101', '102', '161', '162', '152']
['000', '001', '002', '061', '052', '100', '101', '102', '161', '162', '152']
160.5 214.0
['000', '001', '002', '061', '052', '100', '101', '102', '161', '162', '152']
['000', '001', '061', '052', '100', '101', '102', '161', '152']
103.33333333333333 155.0
['000', '001', '061', '052', '100', '101', '102', '161', '152']
['001', '052', '101', '161', '152']
77.5 155.0
['001', '052', '101', '161', '152']
['052', '161']
0.0 151.0
['052', '161']
['161']


In [65]:
buckets

[['062'],
 ['002', '162'],
 ['000', '061', '100', '102'],
 ['001', '101', '152'],
 ['052']]